### ISSUE TITLE
python3.6 wheel is missing from pypi

### ISSUE THREAD

**Issue by anthrotype** [scikit-build/ninja-python-distributions#12]
For some reason the 3.6 wheel for macOS is not present here:

https://pypi.org/project/ninja/#files

Could you please upload one? Thanks!

**Comment by wanchaol** [comment]
Can anyone fix this? seems like it's still not there.

**Comment by jcfr** [comment]
Thanks for the reminder. We should be able to address this before the end of the week

**Comment by jcfr** [comment]
xref #13

**Comment by jcfr** [comment]
Closing. Ninja (and also cmake) wheels for Python 3.6 and 3.7 are now available.

Note that since the release process is on-going all wheels should be available in 30min to 1 hour.

Thanks for your patience

The release process has also been simplified, creating a tag will now be sufficient to trigger the release process and automatically upload the wheels on PyPI.
